basePath: /api/v1
definitions:
  pkg.ErrorResponse:
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
  pkg.SuccessResponse:
    properties:
      data:
        type: object
      message:
        type: string
      statusCode:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Echo Example API
  version: "1.0"
paths:
  /customer:
    post:
      consumes:
      - application/json
      description: Customer registor api.
      parameters:
      - description: Age
        in: formData
        name: age
        required: true
        type: integer
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: FirstName
        in: formData
        name: firstname
        required: true
        type: string
      - description: LastName
        in: formData
        name: lastname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
      summary: Customer registor.
      tags:
      - customer
  /customer/login:
    post:
      consumes:
      - application/json
      description: Customer Login api.
      parameters:
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
      summary: Customer Login.
      tags:
      - customer
  /customer/me:
    get:
      consumes:
      - application/json
      description: Customer get information api.
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
      summary: Customer information.
      tags:
      - customer
  /customer/password:
    patch:
      consumes:
      - application/json
      description: Customer change password api.
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: OldPassword
        in: formData
        name: oldPassword
        required: true
        type: string
      - description: NewPassword
        in: formData
        name: newPassword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
        "500":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.ErrorResponse'
      summary: Customer change password.
      tags:
      - customer
schemes:
- http
swagger: "2.0"
